apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appdynamics-cluster-agent-instrumentation
rules:
  - apiGroups:
      - ""
    resources:
      - pods/log
      - endpoints
      - persistentvolumeclaims
      - resourcequotas
      - nodes
      - events
      - namespaces
      - services
      - configmaps
      - secrets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - create
      - update
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - statefulsets
      - deployments
      - replicasets
    verbs:
      - get
      - watch
      - list
      - update
  - apiGroups:
      - "batch"
      - "extensions"
    resources:
      - "jobs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - appdynamics.com
    resources:
      - '*'
      - clusteragents
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdynamics-cluster-agent-instrumentation
subjects:
  - kind: ServiceAccount
    name: appdynamics-cluster-agent
    namespace: appdynamics
roleRef:
  kind: ClusterRole
  name: appdynamics-cluster-agent-instrumentation
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: appdynamics.com/v1alpha1
kind: InstrumentationAgent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  appName: "I-ClusterAgent"
  controllerUrl: "http://master-saas-controller.e2e.appd-test.com:8090"
  account: "e2e-customer"
  # docker image info
  image: "118762700218.dkr.ecr.ap-south-1.amazonaws.com/cluster-agent:20.4.0-1101"
  serviceAccountName: appdynamics-cluster-agent
  instrumentationMethod: Env
  nsToInstrumentRegex: dev
  #image-info:
  #  java:
  #    image: docker.io/appdynamics/java-agent:latest
  #    agent-mount-path: /opt/appdynamics
  resourcesToInstrument:
    - Deployment
  defaultEnv: JAVA_OPTS
  #defaultInstrumentationTech: java
  defaultAppName: I-ClusterApp
  #instrumentContainer: first
  ### Uncomment the following two lines if you need pull secrets
  #imagePullSecrets:
  #  name: "<your-docker-pull-secret-name>"
  netvizInfo:
    bciEnabled: false
    port: 3892
  namespaceRules:
    - namespaceRegex: dev1
      matchString: "dep1"
    - namespaceRegex: dev2
      matchString: "dep2"
