apiVersion: appdynamics.com/v1alpha1
kind: InfraViz
metadata:
  name: appd-infraviz
  namespace: appdynamics
spec:
  controllerUrl: "https://saas.appdynamics.com"
  account: "customer1"
  globalAccount: "customer2_f48ef359"
  netVizPort: 3892
  enableDockerViz: "true"
  stdoutLogging: true
